spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 294651237830-0mbsdql6nofhs31hh6qvmpg2a10bq5ls.apps.googleusercontent.com
            clientSecret: KeZ2hrD-LgKVoaRCtLLe_-uS
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driverClassName: org.h2.Driver

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 1
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
      # After successfully authenticating with the OAuth2 Provider,
      # we'll be generating an auth token for the user and sending the token to the
      # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
      # We're not using cookies because they won't work well in mobile clients.

  #      - myandroidapp://oauth2/redirect
  #      - myiosapp://oauth2/redirect